title: ⌗ Jali by Latticework
description: specification-driven serverless microservice framework
google_analytics: UA-81234965-1
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
