window.esdocSearchIndex = [
  [
    "jali-srcs/all/@jali-ms/util/src/argument-empty-string-error.js~argumentemptystringerror",
    "class/all/@jali-ms/util/src/argument-empty-string-error.js~ArgumentEmptyStringError.html",
    "<span>ArgumentEmptyStringError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-empty-string-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-error.js~argumenterror",
    "class/all/@jali-ms/util/src/argument-error.js~ArgumentError.html",
    "<span>ArgumentError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-false-error.js~argumentfalseerror",
    "class/all/@jali-ms/util/src/argument-false-error.js~ArgumentFalseError.html",
    "<span>ArgumentFalseError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-false-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-falsy-error.js~argumentfalsyerror",
    "class/all/@jali-ms/util/src/argument-falsy-error.js~ArgumentFalsyError.html",
    "<span>ArgumentFalsyError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-falsy-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-nan-error.js~argumentnanerror",
    "class/all/@jali-ms/util/src/argument-nan-error.js~ArgumentNanError.html",
    "<span>ArgumentNanError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-nan-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-null-error.js~argumentnullerror",
    "class/all/@jali-ms/util/src/argument-null-error.js~ArgumentNullError.html",
    "<span>ArgumentNullError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-null-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-type-error.js~argumenttypeerror",
    "class/all/@jali-ms/util/src/argument-type-error.js~ArgumentTypeError.html",
    "<span>ArgumentTypeError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-type-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-undefined-error.js~argumentundefinederror",
    "class/all/@jali-ms/util/src/argument-undefined-error.js~ArgumentUndefinedError.html",
    "<span>ArgumentUndefinedError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-undefined-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-whitespace-string-error.js~argumentwhitespacestringerror",
    "class/all/@jali-ms/util/src/argument-whitespace-string-error.js~ArgumentWhitespaceStringError.html",
    "<span>ArgumentWhitespaceStringError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-whitespace-string-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-zero-error.js~argumentzeroerror",
    "class/all/@jali-ms/util/src/argument-zero-error.js~ArgumentZeroError.html",
    "<span>ArgumentZeroError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-zero-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/invalid-state-error.js~invalidstateerror",
    "class/all/@jali-ms/util/src/invalid-state-error.js~InvalidStateError.html",
    "<span>InvalidStateError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/invalid-state-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/note/src/message-code.js~messagecode",
    "class/all/@jali-ms/note/src/message-code.js~MessageCode.html",
    "<span>MessageCode</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/note/src/message-code.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html",
    "<span>StandardMessageEncoding</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/note/src/standard-message-encoding.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/core/src/structured-error.js~structurederror",
    "class/all/@jali-ms/core/src/structured-error.js~StructuredError.html",
    "<span>StructuredError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/core/src/structured-error.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/note/src/typed-message.js~typedmessage",
    "class/all/@jali-ms/note/src/typed-message.js~TypedMessage.html",
    "<span>TypedMessage</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/note/src/typed-message.js</span>",
    "class"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~asarray",
    "function/index.html#static-function-asArray",
    "<span>asArray</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~asiterable",
    "function/index.html#static-function-asIterable",
    "<span>asIterable</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~concat",
    "function/index.html#static-function-concat",
    "<span>concat</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/core/src/notification-message-iterables.js~error",
    "function/index.html#static-function-error",
    "<span>error</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/core/src/notification-message-iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~every",
    "function/index.html#static-function-every",
    "<span>every</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/note/src/standard-encodings.js~extended",
    "variable/index.html#static-variable-extended",
    "<span>extended</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/note/src/standard-encodings.js</span>",
    "variable"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~find",
    "function/index.html#static-function-find",
    "<span>find</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/core/src/notification-message-iterables.js~get_errors",
    "function/index.html#static-function-get_Errors",
    "<span>get_Errors</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/core/src/notification-message-iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~includes",
    "function/index.html#static-function-includes",
    "<span>includes</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/type-guards.js~iserror",
    "function/index.html#static-function-isError",
    "<span>isError</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/type-guards.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/type-guards.js~isiterable",
    "function/index.html#static-function-isIterable",
    "<span>isIterable</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/type-guards.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/core/src/type-guards.js~isnotificationmessage",
    "function/index.html#static-function-isNotificationMessage",
    "<span>isNotificationMessage</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/core/src/type-guards.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/note/src/standard-encodings.js~local",
    "variable/index.html#static-variable-local",
    "<span>local</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/note/src/standard-encodings.js</span>",
    "variable"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/type-guards.js~makeisiterable",
    "function/index.html#static-function-makeIsIterable",
    "<span>makeIsIterable</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/type-guards.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~reduce",
    "function/index.html#static-function-reduce",
    "<span>reduce</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~slice",
    "function/index.html#static-function-slice",
    "<span>slice</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~some",
    "function/index.html#static-function-some",
    "<span>some</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/note/src/standard-encodings.js~standard",
    "variable/index.html#static-variable-standard",
    "<span>standard</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/note/src/standard-encodings.js</span>",
    "variable"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/iterables.js~tomap",
    "function/index.html#static-function-toMap",
    "<span>toMap</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/iterables.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifyargument",
    "function/index.html#static-function-verifyArgument",
    "<span>verifyArgument</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifyarray",
    "function/index.html#static-function-verifyArray",
    "<span>verifyArray</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifyboolean",
    "function/index.html#static-function-verifyBoolean",
    "<span>verifyBoolean</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifydefined",
    "function/index.html#static-function-verifyDefined",
    "<span>verifyDefined</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifyfunction",
    "function/index.html#static-function-verifyFunction",
    "<span>verifyFunction</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifyiterable",
    "function/index.html#static-function-verifyIterable",
    "<span>verifyIterable</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifynonempty",
    "function/index.html#static-function-verifyNonEmpty",
    "<span>verifyNonEmpty</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifynonzero",
    "function/index.html#static-function-verifyNonZero",
    "<span>verifyNonZero</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifynotnull",
    "function/index.html#static-function-verifyNotNull",
    "<span>verifyNotNull</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifynotwhitespace",
    "function/index.html#static-function-verifyNotWhitespace",
    "<span>verifyNotWhitespace</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifynumber",
    "function/index.html#static-function-verifyNumber",
    "<span>verifyNumber</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifyobject",
    "function/index.html#static-function-verifyObject",
    "<span>verifyObject</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifystring",
    "function/index.html#static-function-verifyString",
    "<span>verifyString</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifytrue",
    "function/index.html#static-function-verifyTrue",
    "<span>verifyTrue</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "jali-srcs/all/@jali-ms/util/src/argument-verifiers.js~verifytruthy",
    "function/index.html#static-function-verifyTruthy",
    "<span>verifyTruthy</span> <span class=\"search-result-import-path\">jali-srcs/all/@jali-ms/util/src/argument-verifiers.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "all/@jali-ms/core/index.js",
    "file/all/@jali-ms/core/index.js.html",
    "all/@jali-ms/core/index.js",
    "file"
  ],
  [
    "all/@jali-ms/core/iterables/index.js",
    "file/all/@jali-ms/core/iterables/index.js.html",
    "all/@jali-ms/core/iterables/index.js",
    "file"
  ],
  [
    "all/@jali-ms/core/src/message-priority.js",
    "file/all/@jali-ms/core/src/message-priority.js.html",
    "all/@jali-ms/core/src/message-priority.js",
    "file"
  ],
  [
    "all/@jali-ms/core/src/message-severity.js",
    "file/all/@jali-ms/core/src/message-severity.js.html",
    "all/@jali-ms/core/src/message-severity.js",
    "file"
  ],
  [
    "all/@jali-ms/core/src/notification-message-iterables.js",
    "file/all/@jali-ms/core/src/notification-message-iterables.js.html",
    "all/@jali-ms/core/src/notification-message-iterables.js",
    "file"
  ],
  [
    "all/@jali-ms/core/src/notification-message.js",
    "file/all/@jali-ms/core/src/notification-message.js.html",
    "all/@jali-ms/core/src/notification-message.js",
    "file"
  ],
  [
    "all/@jali-ms/core/src/structured-error.js",
    "file/all/@jali-ms/core/src/structured-error.js.html",
    "all/@jali-ms/core/src/structured-error.js",
    "file"
  ],
  [
    "all/@jali-ms/core/src/structured-error.js~structurederror#constructor",
    "class/all/@jali-ms/core/src/structured-error.js~StructuredError.html#instance-constructor-constructor",
    "all/@jali-ms/core/src/structured-error.js~StructuredError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/core/src/structured-error.js~structurederror#innererror",
    "class/all/@jali-ms/core/src/structured-error.js~StructuredError.html#instance-member-innerError",
    "all/@jali-ms/core/src/structured-error.js~StructuredError#innerError",
    "member"
  ],
  [
    "all/@jali-ms/core/src/structured-error.js~structurederror.resolvemessage",
    "class/all/@jali-ms/core/src/structured-error.js~StructuredError.html#static-method-resolveMessage",
    "all/@jali-ms/core/src/structured-error.js~StructuredError.resolveMessage",
    "method"
  ],
  [
    "all/@jali-ms/core/src/type-guards.js",
    "file/all/@jali-ms/core/src/type-guards.js.html",
    "all/@jali-ms/core/src/type-guards.js",
    "file"
  ],
  [
    "all/@jali-ms/core/type-guards/index.js",
    "file/all/@jali-ms/core/type-guards/index.js.html",
    "all/@jali-ms/core/type-guards/index.js",
    "file"
  ],
  [
    "all/@jali-ms/note/index.js",
    "file/all/@jali-ms/note/index.js.html",
    "all/@jali-ms/note/index.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/message-code.js",
    "file/all/@jali-ms/note/src/message-code.js.html",
    "all/@jali-ms/note/src/message-code.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/message-code.js~messagecode#constructor",
    "class/all/@jali-ms/note/src/message-code.js~MessageCode.html#instance-constructor-constructor",
    "all/@jali-ms/note/src/message-code.js~MessageCode#constructor",
    "method"
  ],
  [
    "all/@jali-ms/note/src/message-code.js~messagecode#messagecode",
    "class/all/@jali-ms/note/src/message-code.js~MessageCode.html#instance-member-messageCode",
    "all/@jali-ms/note/src/message-code.js~MessageCode#messageCode",
    "member"
  ],
  [
    "all/@jali-ms/note/src/message-code.js~messagecode#messageencoding",
    "class/all/@jali-ms/note/src/message-code.js~MessageCode.html#instance-member-messageEncoding",
    "all/@jali-ms/note/src/message-code.js~MessageCode#messageEncoding",
    "member"
  ],
  [
    "all/@jali-ms/note/src/message-code.js~messagecode#priority",
    "class/all/@jali-ms/note/src/message-code.js~MessageCode.html#instance-get-priority",
    "all/@jali-ms/note/src/message-code.js~MessageCode#priority",
    "member"
  ],
  [
    "all/@jali-ms/note/src/message-encoding-data.js",
    "file/all/@jali-ms/note/src/message-encoding-data.js.html",
    "all/@jali-ms/note/src/message-encoding-data.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/message-encoding-segment-data.js",
    "file/all/@jali-ms/note/src/message-encoding-segment-data.js.html",
    "all/@jali-ms/note/src/message-encoding-segment-data.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/message-encoding-version.js",
    "file/all/@jali-ms/note/src/message-encoding-version.js.html",
    "all/@jali-ms/note/src/message-encoding-version.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/message-encoding.js",
    "file/all/@jali-ms/note/src/message-encoding.js.html",
    "all/@jali-ms/note/src/message-encoding.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/standard-encodings.js",
    "file/all/@jali-ms/note/src/standard-encodings.js.html",
    "all/@jali-ms/note/src/standard-encodings.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js",
    "file/all/@jali-ms/note/src/standard-message-encoding.js.html",
    "all/@jali-ms/note/src/standard-message-encoding.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#constructor",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-constructor-constructor",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#constructor",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getauthoritycode",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getAuthorityCode",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getAuthorityCode",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getbasemessagecode",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getBaseMessageCode",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getBaseMessageCode",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getdomaincode",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getDomainCode",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getDomainCode",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getlibrarycode",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getLibraryCode",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getLibraryCode",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getmessagepriority",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getMessagePriority",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getMessagePriority",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getmessageseverity",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getMessageSeverity",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getMessageSeverity",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#getvalidversion",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-getValidVersion",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#getValidVersion",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#isvalidcode",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-method-isValidCode",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#isValidCode",
    "method"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#versionmap",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-member-versionMap",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#versionMap",
    "member"
  ],
  [
    "all/@jali-ms/note/src/standard-message-encoding.js~standardmessageencoding#versions",
    "class/all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding.html#instance-member-versions",
    "all/@jali-ms/note/src/standard-message-encoding.js~StandardMessageEncoding#versions",
    "member"
  ],
  [
    "all/@jali-ms/note/src/typed-message.js",
    "file/all/@jali-ms/note/src/typed-message.js.html",
    "all/@jali-ms/note/src/typed-message.js",
    "file"
  ],
  [
    "all/@jali-ms/note/src/typed-message.js~typedmessage#constructor",
    "class/all/@jali-ms/note/src/typed-message.js~TypedMessage.html#instance-constructor-constructor",
    "all/@jali-ms/note/src/typed-message.js~TypedMessage#constructor",
    "method"
  ],
  [
    "all/@jali-ms/note/src/typed-message.js~typedmessage#innermessagecode",
    "class/all/@jali-ms/note/src/typed-message.js~TypedMessage.html#instance-member-innerMessageCode",
    "all/@jali-ms/note/src/typed-message.js~TypedMessage#innerMessageCode",
    "member"
  ],
  [
    "all/@jali-ms/note/src/typed-message.js~typedmessage#messagecode",
    "class/all/@jali-ms/note/src/typed-message.js~TypedMessage.html#instance-get-messageCode",
    "all/@jali-ms/note/src/typed-message.js~TypedMessage#messageCode",
    "member"
  ],
  [
    "all/@jali-ms/note/src/typed-message.js~typedmessage#priority",
    "class/all/@jali-ms/note/src/typed-message.js~TypedMessage.html#instance-get-priority",
    "all/@jali-ms/note/src/typed-message.js~TypedMessage#priority",
    "member"
  ],
  [
    "all/@jali-ms/util/errors/index.js",
    "file/all/@jali-ms/util/errors/index.js.html",
    "all/@jali-ms/util/errors/index.js",
    "file"
  ],
  [
    "all/@jali-ms/util/index.js",
    "file/all/@jali-ms/util/index.js.html",
    "all/@jali-ms/util/index.js",
    "file"
  ],
  [
    "all/@jali-ms/util/iterables/index.js",
    "file/all/@jali-ms/util/iterables/index.js.html",
    "all/@jali-ms/util/iterables/index.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-empty-string-error.js",
    "file/all/@jali-ms/util/src/argument-empty-string-error.js.html",
    "all/@jali-ms/util/src/argument-empty-string-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-empty-string-error.js~argumentemptystringerror#constructor",
    "class/all/@jali-ms/util/src/argument-empty-string-error.js~ArgumentEmptyStringError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-empty-string-error.js~ArgumentEmptyStringError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-error.js",
    "file/all/@jali-ms/util/src/argument-error.js.html",
    "all/@jali-ms/util/src/argument-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-error.js~argumenterror#constructor",
    "class/all/@jali-ms/util/src/argument-error.js~ArgumentError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-error.js~ArgumentError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-false-error.js",
    "file/all/@jali-ms/util/src/argument-false-error.js.html",
    "all/@jali-ms/util/src/argument-false-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-false-error.js~argumentfalseerror#constructor",
    "class/all/@jali-ms/util/src/argument-false-error.js~ArgumentFalseError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-false-error.js~ArgumentFalseError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-falsy-error.js",
    "file/all/@jali-ms/util/src/argument-falsy-error.js.html",
    "all/@jali-ms/util/src/argument-falsy-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-falsy-error.js~argumentfalsyerror#constructor",
    "class/all/@jali-ms/util/src/argument-falsy-error.js~ArgumentFalsyError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-falsy-error.js~ArgumentFalsyError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-falsy-error.js~argumentfalsyerror.makefalsytypedmessage",
    "class/all/@jali-ms/util/src/argument-falsy-error.js~ArgumentFalsyError.html#static-method-makeFalsyTypedMessage",
    "all/@jali-ms/util/src/argument-falsy-error.js~ArgumentFalsyError.makeFalsyTypedMessage",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-nan-error.js",
    "file/all/@jali-ms/util/src/argument-nan-error.js.html",
    "all/@jali-ms/util/src/argument-nan-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-nan-error.js~argumentnanerror#constructor",
    "class/all/@jali-ms/util/src/argument-nan-error.js~ArgumentNanError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-nan-error.js~ArgumentNanError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-null-error.js",
    "file/all/@jali-ms/util/src/argument-null-error.js.html",
    "all/@jali-ms/util/src/argument-null-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-null-error.js~argumentnullerror#constructor",
    "class/all/@jali-ms/util/src/argument-null-error.js~ArgumentNullError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-null-error.js~ArgumentNullError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-type-error.js",
    "file/all/@jali-ms/util/src/argument-type-error.js.html",
    "all/@jali-ms/util/src/argument-type-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-type-error.js~argumenttypeerror#constructor",
    "class/all/@jali-ms/util/src/argument-type-error.js~ArgumentTypeError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-type-error.js~ArgumentTypeError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-type-error.js~argumenttypeerror.maketypemessage",
    "class/all/@jali-ms/util/src/argument-type-error.js~ArgumentTypeError.html#static-method-makeTypeMessage",
    "all/@jali-ms/util/src/argument-type-error.js~ArgumentTypeError.makeTypeMessage",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-undefined-error.js",
    "file/all/@jali-ms/util/src/argument-undefined-error.js.html",
    "all/@jali-ms/util/src/argument-undefined-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-undefined-error.js~argumentundefinederror#constructor",
    "class/all/@jali-ms/util/src/argument-undefined-error.js~ArgumentUndefinedError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-undefined-error.js~ArgumentUndefinedError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-verifiers.js",
    "file/all/@jali-ms/util/src/argument-verifiers.js.html",
    "all/@jali-ms/util/src/argument-verifiers.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-whitespace-string-error.js",
    "file/all/@jali-ms/util/src/argument-whitespace-string-error.js.html",
    "all/@jali-ms/util/src/argument-whitespace-string-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-whitespace-string-error.js~argumentwhitespacestringerror#constructor",
    "class/all/@jali-ms/util/src/argument-whitespace-string-error.js~ArgumentWhitespaceStringError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-whitespace-string-error.js~ArgumentWhitespaceStringError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/argument-zero-error.js",
    "file/all/@jali-ms/util/src/argument-zero-error.js.html",
    "all/@jali-ms/util/src/argument-zero-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/argument-zero-error.js~argumentzeroerror#constructor",
    "class/all/@jali-ms/util/src/argument-zero-error.js~ArgumentZeroError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/argument-zero-error.js~ArgumentZeroError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/invalid-state-error.js",
    "file/all/@jali-ms/util/src/invalid-state-error.js.html",
    "all/@jali-ms/util/src/invalid-state-error.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/invalid-state-error.js~invalidstateerror#constructor",
    "class/all/@jali-ms/util/src/invalid-state-error.js~InvalidStateError.html#instance-constructor-constructor",
    "all/@jali-ms/util/src/invalid-state-error.js~InvalidStateError#constructor",
    "method"
  ],
  [
    "all/@jali-ms/util/src/invalid-state-error.js~invalidstateerror.makemessage",
    "class/all/@jali-ms/util/src/invalid-state-error.js~InvalidStateError.html#static-method-makeMessage",
    "all/@jali-ms/util/src/invalid-state-error.js~InvalidStateError.makeMessage",
    "method"
  ],
  [
    "all/@jali-ms/util/src/iterables.js",
    "file/all/@jali-ms/util/src/iterables.js.html",
    "all/@jali-ms/util/src/iterables.js",
    "file"
  ],
  [
    "all/@jali-ms/util/src/iterables.js~elementaccumulator",
    "typedef/index.html#static-typedef-ElementAccumulator",
    "all/@jali-ms/util/src/iterables.js~ElementAccumulator",
    "typedef"
  ],
  [
    "all/@jali-ms/util/src/iterables.js~elementconverter",
    "typedef/index.html#static-typedef-ElementConverter",
    "all/@jali-ms/util/src/iterables.js~ElementConverter",
    "typedef"
  ],
  [
    "all/@jali-ms/util/src/iterables.js~elementtest",
    "typedef/index.html#static-typedef-ElementTest",
    "all/@jali-ms/util/src/iterables.js~ElementTest",
    "typedef"
  ],
  [
    "all/@jali-ms/util/src/type-guards.js",
    "file/all/@jali-ms/util/src/type-guards.js.html",
    "all/@jali-ms/util/src/type-guards.js",
    "file"
  ],
  [
    "all/@jali-ms/util/type-guards/index.js",
    "file/all/@jali-ms/util/type-guards/index.js.html",
    "all/@jali-ms/util/type-guards/index.js",
    "file"
  ]
]